version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.14.1
    # working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - add_ssh_keys:
        fingerprints:
          - "a4:a0:f2:47:35:3b:94:0d:38:17:d2:8a:96:71:c2:2c"
      - run: yarn deploy
workflows:
  version: 2
  build:
    jobs:
      - build:
        filters:
          branches:
            only:
              - develop
