version: 2.1
jobs:
  build:
    branches:
      - develop
    docker:
      - image: circleci/node:10.14.1
    # working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: yarn deploy
# workflows:
#   build-and-test:
#     jobs:
#       - build-and-test
