version: 2.1
# orbs:
#   node: circleci/node@1.1.6
jobs:
  build:
    # executor:
    #   name: node/default
    docker:
      - image: circleci/node:10.14.1
    # working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
# workflows:
#   build-and-test:
#     jobs:
#       - build-and-test
